# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e258549e980043711eec94c47d4e6e6f95924fb76763d8c12a51ede95787dd3abbb62ab46a165193991bcfc01d5d16875e6e0b38a541bf309f44b0cb103e367f

test:
  secret_key_base: ef5c305ca7e43b21aaaebf3c1118ab8aeaee222300c2e637dfba8a9ecdc5b8998b606df124994a1f68ec380f156e6740c74f96ce519355b9c045fb47b7eeccd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
